# Replace the "backend" object below with the snippet from DecapBridge. We need something here to get the CMS to work locally, but this alone won't work in production
backend:
  name: git-gateway
  branch: main

# Keep this to allow you to edit the cms locally
local_backend: true

# Change url to a link to the image you want to use, no file paths, must be a URL
logo:
  src: "http://localhost:8080/assets/svgs/Logo.svg"
  show_in_header: false

locale: "cs"

# Where should uploaded files be saved
media_folder: "src/assets/images/cms"

# Where should media be served, relative to the base of the built site
public_folder: "/assets/images/cms"

# Slug function configuration
slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"

# Decap CMS Collections
collections:
  - name: "terminy"
    label: "Uvolněné termíny"
    folder: "src/content/terminy"
    create: true
    slug: "{{date}}-{{start}}-{{end}}"
    summary: "{{statusIcon}} {{date}} ({{start}} – {{end}})"

    fields:
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: null

      - label: "Permalink"
        name: "permalink"
        widget: "hidden"
        default: false

      - label: "Datum"
        name: "date"
        widget: "datetime"
        format: "YYYY-MM-DD"
        time_format: false

      - label: "Od"
        name: "start"
        widget: "datetime"
        format: "HH:mm"
        date_format: false

      - label: "Do"
        name: "end"
        widget: "datetime"
        format: "HH:mm"
        date_format: false

      - label: "Publikovat"
        name: "published"
        widget: "boolean"
        default: true
